/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package universidadCravero.vistas;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author crist
 */
public class MenuView extends javax.swing.JFrame {

    /**
     * Creates new form MenuView
     */
    public MenuView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon fondo = new ImageIcon(getClass().getResource("/universidadCravero/recursos/fondo.png"));
        Image miFondo = fondo.getImage();
        desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){

                g.drawImage(miFondo,0,0,getWidth(),getHeight(),this);

            }

        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemAlumnos = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemMateria = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemManjInsc = new javax.swing.JMenuItem();
        jMenuItemManNotas = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItemAlmPorMateria = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 693, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
        );

        jMenu1.setText("Alumnos");

        jMenuItemAlumnos.setText("Formulario Alumno");
        jMenuItemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemAlumnos);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Materia");

        jMenuItemMateria.setText("Formulario Materia");
        jMenuItemMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemMateriaActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItemMateria);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Administración");

        jMenuItemManjInsc.setText("Manejo de Inscripciones");
        jMenuItemManjInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManjInscActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManjInsc);

        jMenuItemManNotas.setText("Manipulación de notas");
        jMenuItemManNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemManNotasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemManNotas);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Consultas");

        jMenuItemAlmPorMateria.setText("Alumnos por materia");
        jMenuItemAlmPorMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlmPorMateriaActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItemAlmPorMateria);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Salir");
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlumnosActionPerformed
        desktop.removeAll();
        desktop.repaint();
        
        FormularioAlumnoView formAlumnoView = new FormularioAlumnoView();
        
        formAlumnoView.setVisible(true);
        formAlumnoView.getContentPane().setBackground(new Color(68, 167, 132));
        desktop.add(formAlumnoView);
        desktop.moveToFront(formAlumnoView);
    }//GEN-LAST:event_jMenuItemAlumnosActionPerformed

    private void jMenuItemMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMateriaActionPerformed
        desktop.removeAll();
        desktop.repaint();
        
        FormularioMateriaView formMateriaView = new FormularioMateriaView();
        formMateriaView.setVisible(true);
        formMateriaView.getContentPane().setBackground(new Color(68, 167, 132));
        
        desktop.add(formMateriaView);
        desktop.moveToFront(formMateriaView);
        
    }//GEN-LAST:event_jMenuItemMateriaActionPerformed

    private void jMenuItemManjInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManjInscActionPerformed
        desktop.removeAll();
        desktop.repaint();
        
        ManejoInscripcionesView manjInscView = new ManejoInscripcionesView();
        manjInscView.setVisible(true);
        manjInscView.getContentPane().setBackground(new Color(68, 167, 132));
        
        desktop.add(manjInscView);
        desktop.moveToFront(manjInscView);
        
    }//GEN-LAST:event_jMenuItemManjInscActionPerformed

    private void jMenuItemManNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemManNotasActionPerformed
        desktop.removeAll();
        desktop.repaint();
        
        ManipulacionNotasView manNotasView = new ManipulacionNotasView();
        manNotasView.setVisible(true);
        manNotasView.getContentPane().setBackground(new Color(68, 167, 132));
        
        desktop.add(manNotasView);
        desktop.moveToFront(manNotasView);
    }//GEN-LAST:event_jMenuItemManNotasActionPerformed

    private void jMenuItemAlmPorMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlmPorMateriaActionPerformed
        desktop.removeAll();
        desktop.repaint();
        
        AlumnosPorMateriaView alMatView = new AlumnosPorMateriaView();
        alMatView.setVisible(true);
        alMatView.getContentPane().setBackground(new Color(68, 167, 132));
        
        desktop.add(alMatView);
        desktop.moveToFront(alMatView);
        
    }//GEN-LAST:event_jMenuItemAlmPorMateriaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlmPorMateria;
    private javax.swing.JMenuItem jMenuItemAlumnos;
    private javax.swing.JMenuItem jMenuItemManNotas;
    private javax.swing.JMenuItem jMenuItemManjInsc;
    private javax.swing.JMenuItem jMenuItemMateria;
    // End of variables declaration//GEN-END:variables
}
